import { Asset, Activity, SystemSettings } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'eth',
    name: 'Ethereum',
    symbol: 'ETH',
    chain: 'MAINNET',
    price: 2450.12,
    change24h: 1.24,
    holdings: 4.502,
    value: 11030.45,
    icon: 'ETH',
  },
  {
    id: 'usdc',
    name: 'USD Coin',
    symbol: 'USDC',
    chain: 'MULTI-CHAIN',
    price: 1.0,
    change24h: 0.0,
    holdings: 6500.0,
    value: 6500.0,
    icon: 'USDC',
  },
  {
    id: 'link',
    name: 'Chainlink',
    symbol: 'LINK',
    chain: 'ETHEREUM',
    price: 18.42,
    change24h: -2.1,
    holdings: 235.12,
    value: 4330.91,
    icon: 'LINK',
  },
  {
    id: 'arb',
    name: 'Arbitrum',
    symbol: 'ARB',
    chain: 'ARBITRUM',
    price: 1.98,
    change24h: 5.4,
    holdings: 1240.0,
    value: 2457.19,
    icon: 'ARB',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'tx-001',
    type: 'Swap',
    title: 'Swapped ETH for USDC',
    description: 'Executed via Uniswap V3 Smart Route',
    fromAmount: '0.45',
    fromSymbol: 'ETH',
    toAmount: '1,085.40',
    toSymbol: 'USDC',
    timestamp: '2026-06-15 01:22 UTC',
    status: 'Completed',
    txHash: '0x3a92...1f8e',
    gasFee: '$10.15',
  },
  {
    id: 'tx-002',
    type: 'Approve',
    title: 'Approve USDC Spend Limit',
    description: 'Granted BANA Multi-Router spend permission',
    fromAmount: 'Unlimited',
    fromSymbol: 'USDC',
    toAmount: '0',
    toSymbol: '',
    timestamp: '2026-06-14 18:45 UTC',
    status: 'Completed',
    txHash: '0x9c12...4b2d',
    gasFee: '$3.40',
  },
  {
    id: 'tx-003',
    type: 'Send',
    title: 'Sent LINK to Cold Wallet',
    description: 'Transferred to Ledger Vault Address',
    fromAmount: '50.00',
    fromSymbol: 'LINK',
    toAmount: '0',
    toSymbol: '',
    timestamp: '2026-06-13 09:12 UTC',
    status: 'Completed',
    txHash: '0xbf78...ee01',
    gasFee: '$6.82',
  },
  {
    id: 'tx-004',
    type: 'Receive',
    title: 'Received Base Protocol Yield',
    description: 'Automated staking bonus tier 2',
    fromAmount: '0.00',
    fromSymbol: '',
    toAmount: '122.50',
    toSymbol: 'ARB',
    timestamp: '2026-06-12 21:00 UTC',
    status: 'Completed',
    txHash: '0xc982...7a4f',
    gasFee: '$0.12',
  },
];

export const DEFAULT_SETTINGS: SystemSettings = {
  mevProtection: true,
  selectedSlippage: '0.5',
  customSlippage: '0.5',
  networkGas: 'Fast',
  rpcUrl: 'https://rpc.bana.institutional/v1/private',
  connectedWallet: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  walletConnected: true,
  activeChain: 'Mainnet',
};
